# This example makes use of an Ubuntu-based NERSC base image 
# that already has MPI built and installed.
#
# This means the you just need to add your app code in and compile it.
#
# To build this example do:
# docker build -t <dockerhubid>/helloworld:v2 -f Dockerfile.v2 .
#
# And to test:
# docker run -it --rm <dockerhubid>/helloworld:v2 /app/hello

FROM nersc/ubuntu-mpi:14.04

ADD helloworld.c /app/

RUN cd /app && mpicc helloworld.c -o /app/hello

ENV PATH=/usr/bin:/bin:/app
